
on:
  issue_comment:
    types: [created]

name: PR auto-formatting command

jobs:
  format:
    if: ${{ github.event.issue.pull_request && (github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER' || github.event.issue.user.id == github.event.comment.user.id) && startsWith(github.event.comment.body, '/format') }}
    name: auto-format
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2
      - name: Checkout the pull request code
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr checkout ${{ github.event.issue.number }}
      - name: Install JuliaFormatter and format
        run: |
          julia -e 'import Pkg; Pkg.add("JuliaFormatter")'
          julia -e 'using JuliaFormatter; format(".")'
      - name: Remove trailing whitespace
        run: |
          find -name '*.jl' -or -name '*.md' -or -name '*.toml' -or -name '*.yml' | while read filename ; do
            # remove any trailing spaces
            sed --in-place -e 's/\s*$//' "$filename"
            # add a final newline if missing
            if [[ -s "$filename" && $(tail -c 1 "$filename" |wc -l) -eq 0 ]] ; then
              echo >> "$filename"
            fi
            # squash superfluous final newlines
            sed -i -e :a -e '/^\n*$/{$d;N;};/\n$/ba' "$filename"
          done
      - name: Commit and push the changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ `git status -s | wc -l` -ne 0 ] ; then
            git config --local user.name "$GITHUB_ACTOR"
            git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
            git commit -a -m "automatic formatting" -m "triggered by @$GITHUB_ACTOR on PR #${{ github.event.issue.number }}"
            if git push
            then gh pr comment ${{ github.event.issue.number }} --body \
              ":heavy_check_mark: auto-formatting triggered by [this comment](${{ github.event.comment.html_url }}) succeeded, commited as `git rev-parse HEAD`"
            else gh pr comment ${{ github.event.issue.number }} --body \
              ":x: auto-formatting triggered by [this comment](${{ github.event.comment.html_url }}) failed, perhaps someone pushed to the PR in the meantime?"
            fi
          else
            echo "No changes, all good!"
          fi
